import getConfig from 'next/config'

const { publicRuntimeConfig } = getConfig()
const {
  ENVIRONMENT,
  DOMAIN_NAME,
  END_POINT,
  FACEBOOK_APP_ID,
  GOOGLE_ANALYTICS_ID,
  HOTJAR_ID,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_SENDER_ID,
  FIREBASE_APP_ID,
  COMPANY_NAME,
  SITE_URL,
  COOKIE_WOW_DATA_CWCID
} = publicRuntimeConfig

export {
  ENVIRONMENT,
  DOMAIN_NAME,
  END_POINT,
  FACEBOOK_APP_ID,
  GOOGLE_ANALYTICS_ID,
  HOTJAR_ID,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_SENDER_ID,
  FIREBASE_APP_ID,
  COMPANY_NAME,
  SITE_URL,
  COOKIE_WOW_DATA_CWCID
}
